### ISSUE TITLE
Loading in glue: led to black screen

### ISSUE THREAD

**Issue by keflavich** [astrofrog/cube_viewer#6]
I tried loading a cube in glue and got a blank/black screen.  The 'level' value was NaN, so I suspect the auto-levels do not ignore NaNs now.  Even after imposing my own levels, though, I could still see only a black screen.

**Comment by astrofrog** [comment]
@keflavich - have you tried outside of glue? (it's pretty easy to use standalone)

**Comment by astrofrog** [comment]
Indeed it looks like the glue viewer was using percentile instead of nanpercentile. Fixed in 3350ace16ec8148b861985d59a399470655b4421. Can you confirm that this fixes it for you?

**Comment by keflavich** [comment]
Tested - yes, it renders now.  And it does indeed work in standalone mode

**Comment by astrofrog** [comment]
Thanks!
